#define _MySetPoints_0_Temperature 250 
#define _MySetPoints_1_Temperature 390 
#define _MySetPoints_2_Temperature 410 
#define _MySetPoints_3_Temperature 430 
#define _MySetPoints_4_Temperature 440
#define _RoastLength 14
#define _GainTemp 30
#define _IntegralTemp .03
#define _PIDIntegralUdateTimeValueTemp 5000
#define _BeanYFlowSetpoint 4
#define _GainFlow 8
#define _IntegralFlow .3
#define _MaxPercentChangeFlow .01   
#define _PIDIntegralUdateTimeValueFlow 500
#define _TempCoilTooHot 850
#define _OpDetailDisplay_x 600
#define _OpDetailDisplay_y 200
#define _ConfigDisplay_x 300
#define _ConfigDisplay_y 300
#define _BeanYflow_avg_size 10
#define _BeanYflow_avg_sizemax 50
#define _TBeanAvgRoll_size 10
#define _TBeanAvgRoll_sizemax 10
#define _TCoilAvgRoll_size 10
#define _TCoilAvgRoll_sizemax 10
#define _FanCoolingBoostPercent 1.5
#define _TimeOpticalFlowDuration 10
#define _TimeReadThermoDuration 500
#define _CoilTempOffSet -400
